`PropsWithClassName` interface is supported
turansky/react-types-kotlin pull request #1
Opened 2021-09-20 20:23 UTC by sgrishchenko

2021-09-20 20:31 UTC, turansky requested changes

2021-09-20 20:31 UTC, turansky commented on buildSrc/src/main/kotlin/com/github/turansky/react/MemberConverter.kt
> +        .filter { !it.contains("className") }
`startWith("className:")`?

2021-09-20 21:06 UTC, sgrishchenko commented on buildSrc/src/main/kotlin/com/github/turansky/react/MemberConverter.kt
> +        .filter { !it.contains("className") }
it does not work. It seems `SVGAttributes` starts with comment, so `className` is not filtered out for `SVGAttributes` and `SVGAttributes` breaks compilation.

2021-09-20 21:27 UTC, turansky commented on buildSrc/src/main/kotlin/com/github/turansky/react/MemberConverter.kt
> +        .filter { !it.contains("className") }
`"classname:" !in it`?

2021-09-21 06:49 UTC, sgrishchenko commented on buildSrc/src/main/kotlin/com/github/turansky/react/MemberConverter.kt
> +        .filter { !it.contains("className") }
done

2021-09-21 08:49 UTC, merged